
server:
  port: 8081

#   Enabling H2 Console
#   Habilitara o acesso ao console do banco de dados
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:C:/Users/iDavid/Documents/live/projectreuniaodb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

